### ISSUE TITLE
Funcionalidad para nombres compuestos de usuarios

### ISSUE THREAD

**Issue by RichRico** [Rub21/osm-obj-info#8]
@Rub21 

En este caso el nombre de usuario está compuesto de dos palabras, y si deseamos saber el nivel de mapeador del usario no puede redirigir a la pagina para visualizarlo.

![osm](https://cloud.githubusercontent.com/assets/8484029/16852738/e5e47be6-49ce-11e6-88dc-c34b29acee9f.png)

**Comment by Rub21** [comment]
no nex actions here.
